version: "2.4"
services:
  db01:
    image: ustcweizhou/mariadb-cluster:latest
    hostname: db01
    networks:
        br-db:
            ipv4_address: 172.16.10.11
    volumes:
      - /docker/db01:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin", "-uroot", "-pcloudstack", "ping"]
        interval: 10s
        timeout: 10s
        retries: 60
        start_period: 10s
    environment:
      - NODE_NAME=db01
      - CLUSTER_ADDRESS=gcomm://db01,db02,db03
      - DB_ROOT_PASSWORD=cloudstack
      - DB_MARIABACKUP_PASSWORD=cloudstack

  db02:
    image: ustcweizhou/mariadb-cluster:latest
    hostname: db02
    depends_on:
        db01:
            condition: service_healthy
    networks:
        br-db:
            ipv4_address: 172.16.10.12
    volumes:
      - /docker/db02:/var/lib/mysql
    environment:
      - NODE_NAME=db02
      - CLUSTER_ADDRESS=gcomm://db01,db02,db03
      - DB_ROOT_PASSWORD=cloudstack
      - DB_MARIABACKUP_PASSWORD=cloudstack
      
  db03:
    image: ustcweizhou/mariadb-cluster:latest
    hostname: db03
    depends_on:
        db01:
            condition: service_healthy
    networks:
        br-db:
            ipv4_address: 172.16.10.13
    volumes:
      - /docker/db03:/var/lib/mysql
    environment:
      - NODE_NAME=db03
      - CLUSTER_ADDRESS=gcomm://db01,db02,db03
      - DB_ROOT_PASSWORD=cloudstack
      - DB_MARIABACKUP_PASSWORD=cloudstack

  dbvip:
    image: nginx
    hostname: dbvip
    networks:
        br-db:
            ipv4_address: 172.16.10.14
    ports:
        - "13306:3306"
    volumes:
      - ./nginx-galera.conf:/etc/nginx/nginx.conf
    depends_on:
        db01:
            condition: service_healthy

networks:
    br-db:
        driver: bridge
        driver_opts:
            com.docker.network.bridge.name: "br-db"
        ipam:
            driver: default
            config:
                - subnet: 172.16.10.0/24
                  gateway: 172.16.10.254
